### ISSUE TITLE
bootstrap-salt step fails, curl error

### ISSUE THREAD

**Issue by ssplatt** [saltstack/kitchen-salt#115]
Same result with local vagrant driver, on travis-ci using docker driver, and using Linode driver. 
 This log is from a local, vagrant driver, bento/debian-8.7 kitchen converge:
```
       sh: 1: salt-call: not found
       downloading https://bootstrap.saltstack.org
         to file /tmp/bootstrap-salt.sh
       trying wget...
       trying curl...
         % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
       trying perl...
       A URI can't be a ARRAY reference at /usr/share/perl5/LWP/Simple.pm line 64.
       trying python...
       Traceback (most recent call last):
         File "<string>", line 1, in <module>
         File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
           return opener.open(url, data, timeout)
         File "/usr/lib/python2.7/urllib2.py", line 431, in open
           response = self._open(req, data)
         File "/usr/lib/python2.7/urllib2.py", line 449, in _open
           '_open', req)
         File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
           result = func(*args)
         File "/usr/lib/python2.7/urllib2.py", line 1240, in https_open
           context=self._context)
         File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
           raise URLError(err)
       urllib2.URLError: <urlopen error [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:581)>
>>>>>> wget, curl, fetch, perl or python not found on this instance.
       sh: 1: salt-call: not found
```

```
artifactory (2.8.2)
bigdecimal (1.3.2, default: 1.3.0)
builder (3.2.3)
CFPropertyList (2.3.5)
did_you_mean (1.1.2)
excon (0.57.0)
fission (0.5.0)
fog (1.40.0)
fog-aliyun (0.1.0)
fog-atmos (0.1.0)
fog-aws (1.4.0)
fog-brightbox (0.11.0)
fog-cloudatcost (0.1.2)
fog-core (1.44.3)
fog-digitalocean (0.3.0)
fog-dnsimple (1.0.0)
fog-dynect (0.0.3)
fog-ecloud (0.3.0)
fog-google (0.1.0)
fog-json (1.0.2)
fog-local (0.3.1)
fog-openstack (0.1.21)
fog-powerdns (0.1.1)
fog-profitbricks (3.0.0)
fog-rackspace (0.1.5)
fog-radosgw (0.0.5)
fog-riakcs (0.1.0)
fog-sakuracloud (1.7.5)
fog-serverlove (0.1.2)
fog-softlayer (1.1.4)
fog-storm_on_demand (0.1.1)
fog-terremark (0.1.0)
fog-vmfusion (0.1.0)
fog-voxel (0.1.0)
fog-vsphere (1.11.0)
fog-xenserver (0.3.0)
fog-xml (0.1.3)
formatador (0.2.5)
inflecto (0.0.2)
io-console (default: 0.4.6)
ipaddress (0.8.3)
json (2.1.0, default: 2.0.2, 1.8.6)
kitchen-linode (0.14.0)
kitchen-salt (0.0.26)
kitchen-vagrant (1.1.0)
mini_portile2 (2.2.0)
minitest (5.10.2)
mixlib-install (2.1.12)
mixlib-shellout (2.2.7)
mixlib-versioning (1.1.0)
multi_json (1.12.1)
net-scp (1.2.1)
net-ssh (4.1.0)
net-ssh-gateway (1.3.0)
net-telnet (0.1.1)
nokogiri (1.8.0)
openssl (2.0.4, default: 2.0.2)
power_assert (1.0.2)
psych (2.2.4, default: 2.2.2)
rake (12.0.0)
rbvmomi (1.11.3)
rdoc (5.1.0, default: 5.0.0)
rubygems-update (2.6.12)
safe_yaml (1.0.4)
test-kitchen (1.16.0)
test-unit (3.2.5)
thor (0.19.1)
trollop (2.1.2)
xml-simple (1.1.5)
xmlrpc (0.3.0)
```

```
ruby 2.4.0
```

**Comment by kgeorgak** [comment]
We were getting this error as well and asked Saltstack on Twitter. They said to use `https://bootstrap.saltstack.com` instead which is the official from the docs. 

This is configurable in kitchen-salt via the `salt_bootstrap_url` provisioner option. Weirdly, the default seems to be `https://bootstrap.saltstack.com` according to the docs but it actually uses `https://bootstrap.saltstack.org` upon execution.

**Comment by gtmanfred** [comment]
This will be fixed in a minute once the tests finish running.
