### ISSUE TITLE
Dependencies Example isn't working

### ISSUE THREAD

**Issue by bradenwright** [saltstack/kitchen-salt#130]
My .kitchen.yml file:

```
---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  dependencies:
    - name: nginx
      repo: git
      source: https://github.com/salt-formulas/salt-formula-nginx.git
  is_file_root: true
  require_chef: false
  state_top:
    base:
      '*':
        - jenkins-master

platforms:
- name: ubuntu-16.04

suites:
- name: default
```

Error:
```
ip-10-100-5-96:jenkins braden$ kit test
-----> Starting Kitchen (v1.16.0)
-----> Cleaning up any prior instances of <default-ubuntu-1604>
-----> Destroying <default-ubuntu-1604>...
       ==> default: Forcing shutdown of VM...
       ==> default: Destroying VM and associated drives...
       Vagrant instance <default-ubuntu-1604> destroyed.
       Finished destroying <default-ubuntu-1604> (0m4.29s).
-----> Testing <default-ubuntu-1604>
-----> Creating <default-ubuntu-1604>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'bento/ubuntu-16.04'...
==> default: Matching MAC address for NAT networking...
       ==> default: Checking if box 'bento/ubuntu-16.04' is up to date...
       ==> default: A newer version of the box 'bento/ubuntu-16.04' is available! You currently
       ==> default: have version '2.3.5'. The latest is version '2.3.7'. Run
       ==> default: `vagrant box update` to update.
       ==> default: Setting the name of the VM: kitchen-jenkins-default-ubuntu-1604_default_1501784455236_57941
       ==> default: Fixed port collision for 22 => 2222. Now on port 2200.
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 22 (guest) => 2200 (host) (adapter 1)
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 127.0.0.1:2200
           default: SSH username: vagrant
           default: SSH auth method: private key
           default: 
           default: Vagrant insecure key detected. Vagrant will automatically replace
           default: this with a newly generated keypair for better security.
           default: 
           default: Inserting generated public key within guest...
           default: Removing insecure key from the guest if it's present...
           default: Key inserted! Disconnecting and reconnecting using new SSH key...
       ==> default: Machine booted and ready!
       ==> default: Checking for guest additions in VM...
       ==> default: Setting hostname...
       ==> default: Mounting shared folders...
           default: /tmp/omnibus/cache => /Users/braden/.kitchen/cache
       ==> default: Machine not provisioned because `--no-provision` is specified.
       [SSH] Established
       Vagrant instance <default-ubuntu-1604> created.
       Finished creating <default-ubuntu-1604> (0m38.16s).
-----> Converging <default-ubuntu-1604>...
       Preparing files for transfer
       Preparing salt-minion
       Preparing pillars into /srv/pillar
       Preparing state collection
       neither collection_name or formula have been set, assuming this is a pre-built collection
       Preparing formula: nginx from 
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [no implicit conversion of nil into String] on default-ubuntu-1604
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Logs:
```
$ cat .kitchen/logs/kitchen.log 
I, [2017-08-03T13:26:46.019435 #16856]  INFO -- Kitchen: -----> Starting Kitchen (v1.16.0)
I, [2017-08-03T13:26:46.145603 #16856]  INFO -- Kitchen: -----> Converging <default-ubuntu-1604>...
E, [2017-08-03T13:26:46.177263 #16856] ERROR -- Kitchen: ------Exception-------
E, [2017-08-03T13:26:46.177293 #16856] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-08-03T13:26:46.177307 #16856] ERROR -- Kitchen: Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [no implicit conversion of nil into String] on default-ubuntu-1604
E, [2017-08-03T13:26:46.177319 #16856] ERROR -- Kitchen: ----------------------
E, [2017-08-03T13:26:46.177330 #16856] ERROR -- Kitchen: ------Backtrace-------
E, [2017-08-03T13:26:46.177340 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:183:in `report_errors'
E, [2017-08-03T13:26:46.177351 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:174:in `run_action'
E, [2017-08-03T13:26:46.177361 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:36:in `block in call'
E, [2017-08-03T13:26:46.177372 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-08-03T13:26:46.177382 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:34:in `call'
E, [2017-08-03T13:26:46.177392 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:53:in `perform'
E, [2017-08-03T13:26:46.177402 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:187:in `block (2 levels) in <class:CLI>'
E, [2017-08-03T13:26:46.177413 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
E, [2017-08-03T13:26:46.177423 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
E, [2017-08-03T13:26:46.177433 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:334:in `invoke_task'
E, [2017-08-03T13:26:46.177443 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
E, [2017-08-03T13:26:46.177453 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
E, [2017-08-03T13:26:46.177464 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `block in <top (required)>'
E, [2017-08-03T13:26:46.177474 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2017-08-03T13:26:46.177484 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `<top (required)>'
E, [2017-08-03T13:26:46.177494 #16856] ERROR -- Kitchen: /usr/local/bin/kitchen:21:in `load'
E, [2017-08-03T13:26:46.177504 #16856] ERROR -- Kitchen: /usr/local/bin/kitchen:21:in `<main>'
E, [2017-08-03T13:26:46.177514 #16856] ERROR -- Kitchen: ----End Backtrace-----
E, [2017-08-03T13:26:46.177523 #16856] ERROR -- Kitchen: -Composite Exception--
E, [2017-08-03T13:26:46.177533 #16856] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-08-03T13:26:46.177542 #16856] ERROR -- Kitchen: Message: Failed to complete #converge action: [no implicit conversion of nil into String] on default-ubuntu-1604
E, [2017-08-03T13:26:46.177552 #16856] ERROR -- Kitchen: ----------------------
E, [2017-08-03T13:26:46.177562 #16856] ERROR -- Kitchen: ------Backtrace-------
E, [2017-08-03T13:26:46.177571 #16856] ERROR -- Kitchen: /Users/braden/.chefdk/gem/ruby/2.3.0/gems/kitchen-salt-0.0.24/lib/kitchen/provisioner/salt_solo.rb:411:in `join'
E, [2017-08-03T13:26:46.177617 #16856] ERROR -- Kitchen: /Users/braden/.chefdk/gem/ruby/2.3.0/gems/kitchen-salt-0.0.24/lib/kitchen/provisioner/salt_solo.rb:411:in `prepare_formula'
E, [2017-08-03T13:26:46.177637 #16856] ERROR -- Kitchen: /Users/braden/.chefdk/gem/ruby/2.3.0/gems/kitchen-salt-0.0.24/lib/kitchen/provisioner/salt_solo.rb:210:in `block in create_sandbox'
E, [2017-08-03T13:26:46.177648 #16856] ERROR -- Kitchen: /Users/braden/.chefdk/gem/ruby/2.3.0/gems/kitchen-salt-0.0.24/lib/kitchen/provisioner/salt_solo.rb:209:in `each'
E, [2017-08-03T13:26:46.177659 #16856] ERROR -- Kitchen: /Users/braden/.chefdk/gem/ruby/2.3.0/gems/kitchen-salt-0.0.24/lib/kitchen/provisioner/salt_solo.rb:209:in `create_sandbox'
E, [2017-08-03T13:26:46.177669 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/base.rb:65:in `call'
E, [2017-08-03T13:26:46.177681 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:384:in `block in converge_action'
E, [2017-08-03T13:26:46.177765 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-08-03T13:26:46.177776 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-08-03T13:26:46.177786 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-08-03T13:26:46.177796 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-08-03T13:26:46.177807 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:380:in `converge_action'
E, [2017-08-03T13:26:46.177817 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-08-03T13:26:46.177827 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-08-03T13:26:46.177837 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-08-03T13:26:46.177877 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:135:in `converge'
E, [2017-08-03T13:26:46.177888 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-08-03T13:26:46.177898 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-08-03T13:26:46.177907 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-08-03T13:26:46.177917 #16856] ERROR -- Kitchen: ----End Backtrace-----
E, [2017-08-03T13:26:46.177927 #16856] ERROR -- Kitchen: ---Nested Exception---
E, [2017-08-03T13:26:46.177938 #16856] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-08-03T13:26:46.177975 #16856] ERROR -- Kitchen: Message: Failed to complete #converge action: [no implicit conversion of nil into String]
E, [2017-08-03T13:26:46.177986 #16856] ERROR -- Kitchen: ----------------------
E, [2017-08-03T13:26:46.177995 #16856] ERROR -- Kitchen: ------Backtrace-------
E, [2017-08-03T13:26:46.178005 #16856] ERROR -- Kitchen: /Users/braden/.chefdk/gem/ruby/2.3.0/gems/kitchen-salt-0.0.24/lib/kitchen/provisioner/salt_solo.rb:411:in `join'
E, [2017-08-03T13:26:46.178014 #16856] ERROR -- Kitchen: /Users/braden/.chefdk/gem/ruby/2.3.0/gems/kitchen-salt-0.0.24/lib/kitchen/provisioner/salt_solo.rb:411:in `prepare_formula'
E, [2017-08-03T13:26:46.178024 #16856] ERROR -- Kitchen: /Users/braden/.chefdk/gem/ruby/2.3.0/gems/kitchen-salt-0.0.24/lib/kitchen/provisioner/salt_solo.rb:210:in `block in create_sandbox'
E, [2017-08-03T13:26:46.178039 #16856] ERROR -- Kitchen: /Users/braden/.chefdk/gem/ruby/2.3.0/gems/kitchen-salt-0.0.24/lib/kitchen/provisioner/salt_solo.rb:209:in `each'
E, [2017-08-03T13:26:46.178050 #16856] ERROR -- Kitchen: /Users/braden/.chefdk/gem/ruby/2.3.0/gems/kitchen-salt-0.0.24/lib/kitchen/provisioner/salt_solo.rb:209:in `create_sandbox'
E, [2017-08-03T13:26:46.178103 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/base.rb:65:in `call'
E, [2017-08-03T13:26:46.178114 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:384:in `block in converge_action'
E, [2017-08-03T13:26:46.178124 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-08-03T13:26:46.178134 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-08-03T13:26:46.178144 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-08-03T13:26:46.178154 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-08-03T13:26:46.178163 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:380:in `converge_action'
E, [2017-08-03T13:26:46.178176 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-08-03T13:26:46.178187 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-08-03T13:26:46.178197 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-08-03T13:26:46.178207 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:135:in `converge'
E, [2017-08-03T13:26:46.178217 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-08-03T13:26:46.178227 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-08-03T13:26:46.178253 #16856] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-08-03T13:26:46.178304 #16856] ERROR -- Kitchen: ----End Backtrace-----
```

I'm fairly new to salt but have used test-kitchen with Chef a lot.  I tried different options like dependencies from local path instead of from Git.  Really I want to use a jenkins-formula on git, but when that didn't work I just tried to get one of the examples working.

Versions I'm using:

```
ip-10-100-5-96:jenkins braden$ chef gem list |grep kitchen
kitchen-docker (2.6.0)
kitchen-dokken (2.1.2)
kitchen-ec2 (1.3.2)
kitchen-inspec (0.17.0)
kitchen-salt (0.0.24)
kitchen-vagrant (1.1.0)
test-kitchen (1.16.0)
```

Thanks for any help

**Comment by bradenwright** [comment]
Example I was trying to follow: https://github.com/saltstack/kitchen-salt/blob/master/provisioner_options.md#dependencies

**Comment by bradenwright** [comment]
My bad I had the latest version install but it was picking up the old version still.  Once I got kitchen-salt upgrade properly it started working.

I noticed that file path version was working and when I looked at code/error line, that code was in an older version, I removed the old version and it's all good now!
