### ISSUE TITLE
Problem with run command Kitchen Test

### ISSUE THREAD

**Issue by lelix** [saltstack/kitchen-salt#47]
I add `set :backend, :exec` in the spec_helper.rb
but I got a new error

```
           default: Guest Additions Version: 5.0.16
           default: VirtualBox Version: 4.3
       ==> default: Setting hostname...
       ==> default: Machine not provisioned because `--no-provision` is specified.
       [SSH] Established
       Vagrant instance <default-ubuntu-1204> created.
       Finished creating <default-ubuntu-1204> (0m43.64s).
-----> Converging <default-ubuntu-1204>...
       Preparing files for transfer
       Preparing salt-minion
       Preparing state_top
       Preparing pillars into /srv/pillar
       Preparing formula: beaver from /home/lelixone/diego/kitchen-salt-tutorial/beaver-formula
       Preparing formula: Gemfile.lock.back from /home/lelixone/diego/kitchen-salt-tutorial/beaver-formula/
       Preparing formula: top.sls from /home/lelixone/diego/kitchen-salt-tutorial/beaver-formula/
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [File exists @ dir_s_mkdir - /tmp/default-ubuntu-1204-sandbox-20160426-7226-dsoary/srv/salt/top.sls]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

zlib(finalizer): the stream was freed prematurely.
```

**Comment by cmarzullo** [comment]
Love to help you out some here. I use kitchen-salt quite a bit. But missing some information here. You talk about adding the `set :backend ...` that happens in the verifier piece. But it doesn't look like you are getting that far. Your formula is dying on the converge step, which happens way before you get to the serverspec verifier.

What commands are you typing? I haven't used the beaver formula. You may have some success with a formula skeleton generator I wrote: https://github.com/cmarzullo/saltscaffold  You can run that with something like `saltscaffold -p test` followed by `kitchen converge` That will give you a sense of how I use  kitchen-salt.

**Comment by lelix** [comment]
@cmarzullo I follow the instructions https://github.com/simonmcc/kitchen-salt/blob/master/INTRODUCTION.md
but i got error after installing serverspec

```
-----> Running serverspec test suite
-----> Installing Serverspec..
Fetching: sfl-2.2.gem (100%)
Fetching: net-telnet-0.1.1.gem (100%)
Fetching: net-ssh-3.1.1.gem (100%)
Fetching: net-scp-1.2.1.gem (100%)
Fetching: specinfra-2.57.0.gem (100%)
Fetching: rspec-support-3.4.1.gem (100%)
Fetching: diff-lcs-1.2.5.gem (100%)
Fetching: rspec-expectations-3.4.0.gem (100%)
Fetching: rspec-core-3.4.4.gem (100%)
Fetching: rspec-its-1.2.0.gem (100%)
Fetching: rspec-mocks-3.4.1.gem (100%)
Fetching: rspec-3.4.0.gem (100%)
Fetching: multi_json-1.11.3.gem (100%)
Fetching: serverspec-2.32.0.gem (100%)
-----> serverspec installed (version 2.32.0)
       /opt/chef/embedded/bin/ruby -I/tmp/verifier/suites/serverspec -I/tmp/verifier/gems/gems/rspec-support-3.4.1/lib:/tmp/verifier/gems/gems/rspec-core-3.4.4/lib /opt/chef/embedded/bin/rspec --pattern /tmp/verifier/suites/serverspec/\*\*/\*_spec.rb --color --format documentation --default-path /tmp/verifier/suites/serverspec
       /tmp/verifier/suites/serverspec/beaver_spec.rb:3:in `<top (required)>': uninitialized constant Serverspec::Helper::Exec (NameError)
        from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
        from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
        from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
        from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
        from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
        from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
        from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
        from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
        from /tmp/verifier/gems/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
        from /opt/chef/embedded/bin/rspec:22:in `load'
        from /opt/chef/embedded/bin/rspec:22:in `<main>'
       /opt/chef/embedded/bin/ruby -I/tmp/verifier/suites/serverspec -I/tmp/verifier/gems/gems/rspec-support-3.4.1/lib:/tmp/verifier/gems/gems/rspec-core-3.4.4/lib /opt/chef/embedded/bin/rspec --pattern /tmp/verifier/suites/serverspec/\*\*/\*_spec.rb --color --format documentation --default-path /tmp/verifier/suites/serverspec failed
       !!!!!! Ruby Script [/tmp/verifier/gems/gems/busser-serverspec-0.5.9/lib/busser/runner_plugin/../serverspec/runner.rb /tmp/verifier/suites/serverspec] exit code was 1
>>>>>> Verify failed on instance <default-ubuntu-1204>.
>>>>>> Please see .kitchen/logs/default-ubuntu-1204.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

BUSSER_ROOT="/tmp/verifier"; export BUSSER_ROOT
GEM_HOME="/tmp/verifier/gems"; export GEM_HOME
GEM_PATH="/tmp/verifier/gems"; export GEM_PATH
GEM_CACHE="/tmp/verifier/gems/cache"; export GEM_CACHE

sudo -E /tmp/verifier/bin/busser test
']
>>>>>> ----------------------
zlib(finalizer): the stream was freed prematurely.
```

**Comment by cmarzullo** [comment]
not sure but it does seem to be complaining about these lines: https://github.com/simonmcc/beaver-formula/blob/master/test/integration/default/serverspec/beaver_spec.rb#L3-L4 

I'm not sure what those lines are for, as I don't use them. The errors you are seeing are about those lines.

**Comment by epcim** [comment]
any conclusion here? I have had the same issue even for the converge (first empty suit), without any modification of the demo for kitchen salt. 

`Message: Failed to complete #converge action: [File exists @ dir_s_mkdir - /tmp/default-ubuntu-1204-sandbox-20160426-7226-dsoary/srv/salt/top.sls]`

```
Chef Development Kit Version: 0.14.25
chef-client version: 12.10.24
berks version: 4.3.3
kitchen version: 1.8.0
```

**Comment by barkingfoodog** [comment]
Do you have a `top.sls` in your project root? It sounds like the provisioner is trying to copy one over but it already exists. `top.sls` is built by the provisioner from the test duties. You can skip copying yours by adding this to your `.kitchen.yml`:

```
provisioner:
  salt_copy_filter:
    - top.sls
```

**Comment by gtmanfred** [comment]
Yeah, it looks like what is happening is the `top.sls` from your top.sls formula is trying to overwrite the `top.sls` that is laid down by `state_top`.

You will need to disable one of them, and either don't pass anything to `state_top`

Thanks,
Daniel
